platform :ios, '9.0'
target "ShaHaiZiT" do

pod 'AFNetworking', '~> 3.2.1'
pod 'IQKeyboardManager', '~> 5.0.8'
pod 'MJRefresh', '~> 3.1.15.7'
pod 'SDCycleScrollView', '~> 1.75'
pod 'JCAlertController', '~> 3.0.1'
pod 'Masonry', '~> 1.1.0'
pod 'WechatOpenSDK'
pod 'UMCCommon'
pod 'UMCAnalytics', '~> 5.4.1'
pod 'UMCErrorCatch'
pod 'UMCShare/UI'
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/ReducedQQ'
pod 'UMCShare/Social/ReducedSina'
pod 'FMDB', '~> 2.7.2'
pod 'NinaPagerView', '~> 1.6.3'

pod 'MJExtension', '~> 3.0.15.1'
pod 'FSCalendar', '~> 2.7.9'
pod 'JPush', '~> 3.1.0'
pod 'ReactiveObjC', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SDWebImage', '~> 4.4.2'
pod 'RongCloudIM/IMLib', '~> 2.9.3'
pod 'RongCloudIM/IMKit', '~> 2.9.3'
pod 'Qiniu', '~> 7.2.4'
pod 'JSBadgeView', '~> 1.4.1'
pod 'SKTagView', '~> 0.9.2'
pod 'HXPhotoPicker', '~> 2.2.5'
pod 'ZFPlayer', '~> 3.2.3'
pod 'ZFPlayer/ControlView', '~> 3.2.3'
pod 'ZFPlayer/AVPlayer', '~> 3.2.3'
pod 'SPPageMenu', '~> 2.5.5'
pod 'YYText', '~> 1.0.7'

end
